const { test } = require('node:test');
const assert = require('node:assert/strict');
const C = require('../js/core.js');
const S = require('../js/store.js');
const now = new Date('2026-09-29T10:00:00+08:00');
const form = (extra = {}) => ({ type: 'lost', title: '蓝色保温杯', category: '生活用品', area: '图书馆', location: '图书馆二楼', eventDate: '2026-09-28', description: '蓝色杯身，银色杯盖。', nickname: '同学甲', contactType: '邮箱', contact: 'test@example.com', photo: '', ...extra });
const post = (extra = {}, owner = 'owner-a', id = 'post-a') => C.createPost(form(extra), owner, now, id).post;
function memory() { const m = new Map(); return { getItem: k => m.has(k) ? m.get(k) : null, setItem: (k, v) => m.set(k, v), removeItem: k => m.delete(k) }; }

test('01 正常发布寻物，初始状态为寻找中', () => { const p = post(); assert.equal(C.statusLabel(p), '寻找中'); assert.equal(p.ownerId, 'owner-a'); });
test('02 正常发布招领，初始状态为待认领', () => assert.equal(C.statusLabel(post({ type: 'found' })), '待认领'));
test('03 去掉首尾空格再保存', () => assert.equal(C.validatePost(form({ title: '  校园卡  ' })).data.title, '校园卡'));
test('04 空白必填字段返回逐字段错误', () => { const r = C.validatePost(form({ title: ' ', location: '', description: '', nickname: '', contact: '' })); assert.equal(r.ok, false); for (const k of ['title', 'location', 'description', 'nickname', 'contact']) assert.ok(r.errors[k]); });
test('05 名称长度 40 合法，41 被拒绝', () => { assert.ok(C.validatePost(form({ title: '卡'.repeat(40) })).ok); assert.ok(C.validatePost(form({ title: '卡'.repeat(41) })).errors.title); });
test('06 描述长度下界与上界', () => { assert.ok(C.validatePost(form({ description: '字'.repeat(5) })).ok); assert.ok(C.validatePost(form({ description: '字'.repeat(500) })).ok); assert.ok(C.validatePost(form({ description: '字'.repeat(4) })).errors.description); assert.ok(C.validatePost(form({ description: '字'.repeat(501) })).errors.description); });
test('07 非法枚举均被拒绝', () => { const r = C.validatePost(form({ type: 'admin', category: '不存在', area: '不存在', contactType: '未知' })); for (const k of ['type', 'category', 'area', 'contactType']) assert.ok(r.errors[k]); });
test('08 校验真实日历日期与闰年', () => { assert.ok(C.isDate('2024-02-29')); assert.equal(C.isDate('2026-02-29'), false); assert.equal(C.isDate('2026-02-31'), false); assert.equal(C.isDate('2026-13-01'), false); assert.equal(C.isDate('1999-12-31'), false); });
test('09 今天可发布，未来不可发布', () => { assert.ok(C.validatePost(form({ eventDate: '2026-09-29' }), '2026-09-29').ok); assert.ok(C.validatePost(form({ eventDate: '2026-09-30' }), '2026-09-29').errors.eventDate); });
test('10 手机、QQ、邮箱、微信的有效格式', () => { for (const [contactType, contact] of [['手机', '13800000000'], ['QQ', '12345'], ['邮箱', 'a@b.cn'], ['微信', 'student_01']]) assert.ok(C.validatePost(form({ contactType, contact })).ok); });
test('11 无效联系方式返回错误', () => { for (const [contactType, contact] of [['手机', '123'], ['QQ', '01234'], ['邮箱', 'a@b'], ['微信', '123456']]) assert.ok(C.validatePost(form({ contactType, contact })).errors.contact); });
test('12 缺少发布者不能创建记录', () => assert.equal(C.createPost(form(), '', now, 'x').ok, false));
test('13 寻物仅由发布者完成，并派生已找到状态', () => { const r = C.completePost([post()], 'post-a', 'owner-a', now); assert.ok(r.ok); assert.equal(C.statusLabel(r.posts[0]), '已找到'); });
test('14 招领完成后为已归还', () => { const r = C.completePost([post({ type: 'found' })], 'post-a', 'owner-a'); assert.equal(C.statusLabel(r.posts[0]), '已归还'); });
test('15 非发布者、空身份不可修改', () => { assert.equal(C.completePost([post()], 'post-a', 'owner-b').ok, false); assert.equal(C.canManage(post(), ''), false); });
test('16 演示记录即使 ownerId 相同也不可修改', () => assert.equal(C.completePost([{ ...post(), demo: true }], 'post-a', 'owner-a').ok, false));
test('17 不存在的 ID、重复完成均返回失败', () => { assert.equal(C.completePost([post()], 'missing', 'owner-a').ok, false); assert.equal(C.completePost([{ ...post(), status: 'done' }], 'post-a', 'owner-a').ok, false); });
test('18 更新返回新数组，原始记录不变', () => { const p = post(); const a = [p]; C.completePost(a, 'post-a', 'owner-a'); assert.equal(p.status, 'active'); });
test('19 搜索物品名称、描述和地点', () => { for (const keyword of ['保温', '银色', '二楼']) assert.equal(C.queryPosts([post()], { keyword }).length, 1); });
test('20 多关键词采用 AND，大小写和全角兼容', () => { const a = [post({ title: 'USB 充电器', location: 'A楼' })]; assert.equal(C.queryPosts(a, { keyword: 'ｕｓｂ A楼' }).length, 1); assert.equal(C.queryPosts(a, { keyword: 'USB 食堂' }).length, 0); });
test('21 空关键词返回范围内全部，无结果为空数组', () => { assert.equal(C.queryPosts([post()], { keyword: '   ' }).length, 1); assert.deepEqual(C.queryPosts([post()], { keyword: '不存在' }), []); });
test('22 类型、分类、区域、状态组合筛选', () => { const a = [post(), post({ type: 'found', area: '食堂' }, 'owner-b', 'post-b')]; assert.equal(C.queryPosts(a, { type: 'found', category: '生活用品', area: '食堂', status: 'active' }).length, 1); assert.equal(C.queryPosts(a, { type: 'found', area: '图书馆' }).length, 0); });
test('23 我的发布按 ownerId 过滤', () => assert.equal(C.queryPosts([post(), post({}, 'owner-b', 'post-b')], { ownerId: 'owner-a' }).length, 1));
test('24 默认时间倒序且不修改原数组', () => { const a = [post(), { ...post({}, 'b', 'b'), createdAt: '2026-09-30T00:00:00.000Z' }]; assert.equal(C.queryPosts(a)[0].id, 'b'); assert.equal(a[0].id, 'post-a'); });
test('25 按发生日期排序', () => { const a = [post(), post({ eventDate: '2026-09-29' }, 'b', 'b')]; assert.equal(C.queryPosts(a, { sort: 'event' })[0].id, 'b'); });
test('26 默认进行中筛选隐藏完成记录，全部可查', () => { const a = [{ ...post(), status: 'done' }]; assert.equal(C.queryPosts(a, { status: 'active' }).length, 0); assert.equal(C.queryPosts(a, { status: 'all' }).length, 1); });
test('27 HTML 特殊字符安全转义', () => assert.equal(C.escapeHTML('<img src="x" onerror=\'alert(1)\'>&'), '&lt;img src=&quot;x&quot; onerror=&#39;alert(1)&#39;&gt;&amp;'));
test('28 图片拒绝脚本、远程网址、SVG 和过大数据', () => { for (const v of ['javascript:alert(1)', 'https://example.com/a.jpg', 'data:image/svg+xml;base64,AAAA', 'data:image/png;base64,' + 'A'.repeat(420000)]) assert.equal(C.isPhoto(v), false); assert.ok(C.isPhoto('data:image/png;base64,AAAA')); });
test('29 初次读取写入样例和身份，再次读取保留原身份', () => { const m = memory(); const a = S.load(m, [post()], 'a'); assert.ok(a.ok); const b = S.load(m, [], 'b'); assert.equal(b.state.ownerId, 'a'); assert.equal(b.state.posts.length, 1); });
test('30 发布及完成状态可持久化读回', () => { const m = memory(); const state = S.load(m, [], 'owner-a').state; state.posts = C.completePost([post()], 'post-a', 'owner-a').posts; assert.ok(S.save(m, state).ok); assert.equal(S.load(m).state.posts[0].status, 'done'); });
test('31 损坏 JSON 不覆盖原始记录', () => { const m = memory(); m.setItem(S.KEY, '{invalid'); assert.equal(S.load(m, [], 'a').ok, false); assert.equal(m.getItem(S.KEY), '{invalid'); });
test('32 不兼容版本或重复 ID 不允许写入', () => { const m = memory(); assert.equal(S.save(m, { version: 9, ownerId: 'a', posts: [] }).ok, false); assert.equal(S.save(m, { version: 1, ownerId: 'a', posts: [post(), post()] }).ok, false); });
test('33 存储拒绝访问和容量耗尽返回失败', () => { const bad = { getItem() { throw Error('SecurityError'); }, setItem() { throw Error('QuotaExceededError'); } }; assert.equal(S.load(bad, [], 'a').ok, false); assert.equal(S.save(bad, { version: 1, ownerId: 'a', posts: [] }).ok, false); });
test('34 草稿写入、读回、清除', () => { const m = memory(); assert.ok(S.saveDraft(m, form()).ok); assert.equal(S.loadDraft(m).title, '蓝色保温杯'); assert.ok(S.clearDraft(m).ok); assert.equal(S.loadDraft(m), null); });
test('35 损坏或恶意草稿不能注入字段和图片', () => { const m = memory(); m.setItem(S.DRAFT_KEY, 'oops'); assert.equal(S.loadDraft(m), null); m.setItem(S.DRAFT_KEY, JSON.stringify({ title: 123, photo: 'javascript:x', ownerId: 'admin' })); const d = S.loadDraft(m); assert.equal(d.title, ''); assert.equal(d.photo, ''); assert.equal(d.ownerId, undefined); });
test('36 草稿写入与清除失败可被界面识别', () => { const bad = { setItem() { throw Error(); }, removeItem() { throw Error(); } }; assert.equal(S.saveDraft(bad, form()).ok, false); assert.equal(S.clearDraft(bad).ok, false); });
test('37 存储记录校验拒绝缺失类型、状态或时间', () => { for (const change of [{ type: 'x' }, { status: 'x' }, { createdAt: 'bad' }, { demo: 'yes' }, { ownerId: '' }]) assert.equal(C.validPost({ ...post(), ...change }), false); });
test('38 非对象输入返回校验错误而不抛异常', () => { assert.equal(C.validatePost(null).ok, false); assert.equal(C.validatePost('bad').ok, false); });
test('39 原型链属性名不能绕过类型枚举', () => { for (const type of ['__proto__', 'constructor', 'toString']) assert.ok(C.validatePost(form({ type })).errors.type); });
test('40 地点、称呼、联系方式的上界与越界', () => { assert.ok(C.validatePost(form({ location: '楼'.repeat(60), nickname: '甲'.repeat(20), contactType: '邮箱', contact: 'a'.repeat(95) + '@b.cn' })).ok); const r = C.validatePost(form({ location: '楼'.repeat(61), nickname: '甲'.repeat(21), contactType: '邮箱', contact: 'a'.repeat(96) + '@b.cn' })); for (const k of ['location', 'nickname', 'contact']) assert.ok(r.errors[k]); });
test('41 未知类型与状态返回统一兜底文案', () => { assert.equal(C.statusLabel({ type: 'x', status: 'active' }), '未知状态'); assert.equal(C.statusLabel({ type: 'lost', status: 'x' }), '未知状态'); assert.equal(C.statusLabel({ type: 'constructor', status: 'active' }), '未知状态'); });
test('42 发生日期相同时按发布时间倒序', () => { const a = [post(), { ...post({}, 'b', 'b'), createdAt: '2026-09-30T00:00:00.000Z' }]; assert.equal(C.queryPosts(a, { sort: 'event' })[0].id, 'b'); });
